name: Sync Markdown to GitHub Pages

on:
  push:
    branches:
      - master

env:
  ACCOUNT: HAL41
  SOURCE: AI-Insights
  COLLECTION: _ai_insights
  BRANCH: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo ${{ env.SOURCE }}
        uses: actions/checkout@v4

      - name: Copy main README.md
        run: |
          mkdir -p export/$SOURCE
          cp README.md export/${SOURCE}/.

      - name: Generate front matter and organize collection
        run: |
          mkdir -p export/${COLLECTION}
          find archive -type f -name '*.md' | while IFS= read -r file; do
            year_month=$(basename "$(dirname "${file}")")
            lang=$(basename "${file}" .md)
            year=${year_month%-*}
            month=${year_month#*-}
            slug="$lang/$year/$month"
            dest="export/${COLLECTION}/${year_month}-${lang}.md"
            {
              echo '---'
              echo "lang: $lang"
              echo "year: \"$year\""
              echo "month: \"$month\""
              echo "slug: $slug"
              echo '---'
              cat "$file"
            } > "$dest"
          done

      - name: Rewrite image links to raw.githubusercontent URLs
        run: |
          find export -name '*.md' -print0 | while IFS= read -r -d '' file; do
            sed -i 's#\!\[\(.*\)\](\(\.\.\/\)*media/\(.*\))#![\1](https://raw.githubusercontent.com/${{ env.ACCOUNT }}/${{ env.SOURCE }}/${{ env.BRANCH }}/media/\3)#g' "$file"
          done

      - name: Checkout target GitHub Pages repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACCOUNT }}/${{ env.ACCOUNT }}.github.io
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}
          path: gh-pages

      - name: Sync exported content to GH Pages repo
        run: |
          cp -r export/${COLLECTION} gh-pages/
          cp -r export/${SOURCE} gh-pages/
          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${COLLECTION}
          git add ${SOURCE}
          git commit -m "Update from $SOURCE" || echo "No changes to commit"
          git push
